# Generated by Django 3.2.3 on 2021-08-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_email', models.CharField(blank=True, max_length=100, null=True)),
                ('m_phone', models.TextField(blank=True, null=True)),
                ('m_address', models.TextField(blank=True, null=True)),
                ('m_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('trial', models.CharField(blank=True, max_length=100, null=True)),
                ('time_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlansBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_time', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'plans_bought',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('u_password', models.TextField(blank=True, null=True)),
                ('u_name', models.TextField(blank=True, null=True)),
                ('u_address', models.TextField(blank=True, null=True)),
                ('u_phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
